name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependencias
        run: bun install --frozen-lockfile

      - name: Generar Prisma Client
        run: bunx prisma generate

      - name: Validar formato con Prettier
        run: bun run format:check

      - name: Compilar Backend
        run: bun run build

      - name: Ejecutar pruebas
        run: bun run test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependencias
        run: bun install --frozen-lockfile

      - name: Validar formato con Prettier
        run: bun run format:check

      - name: Compilar Frontend
        run: bun run build

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imágenes Docker
        run: docker compose build